-STEP 1
--set up filter in <project root>/.gitattributes that will be committed or in <project root>/.git/info/attributes 
--add filter: *.js filter=localnotes
-STEP 2
--git config --global filter.gitignore.smudge cat
-STEP 3

    --if changes in files result in no conflicts, local notes will be kept (aka a pull is not needed)
    --then local notes are kept and even git pull (because programmed to do rebase) will not overwrite
    --if you need to pull
    --or $git stash save "localnotes" and then git stash apply 
